## Docs: https://hexo.io/docs/configuration.html

# Site
title: Аян Енбекбай
subtitle: iOS, продуктивность, дизайн
theme: yenbekbay-v1
author: Аян Енбекбай
language: ru
timezone: Asia/Almaty

# Metadata
first_name: Аян
last_name: Енбекбай
twitter: yenbekbay
facebook: yenbekbay
email: ayan.yenb@gmail.com
gender: male
fb_admins: 100002863455345
google_analytics: UA-68104290-1
favicon: /images/favicon.png
default_backdrop: almaty_from_ski_jumping_hill.jpg
menu_title: '@yenbekbay'

# Footer links
links:
  -
    title: Twitter
    url: https://twitter.com/yenbekbay
    icon: twitter
  -
    title: GitHub
    url: https://github.com/yenbekbay
    icon: github
  -
    title: Instagram
    url: https://instagram.com/yenbekbay
    icon: instagram
  -
    title: Vimeo
    url: https://vimeo.com/yenbekbay
    icon: vimeo

# Menu
menu:
  -
    title: Blog
    url: /blog
  -
    title: About
    url: /
  -
    title: Timelapses
    url: /timelapses

# Projects
projects:
  -
    title: Сеансы
    description: Лучшее в своем роде iOS приложение для просмотра афиши в кинотеатрах Казахстана.
    image: seansy.png
    year: 2015-2017
    links:
      -
        url: http://seansy.kz/
        title: Перейти на seansy.kz
      -
        url: https://itunes.apple.com/app/id980255991
        title: Скачать с App Store
      -
        url: https://github.com/yenbekbay/seansy
        title: Посмотреть исходный код 
  -
    title: Metio
    description: iOS приложение, показывающее местную погоду на простом языке со всей нужной информацией для принятия решения.
    image: metio.png
    year: 2015-2018
    links:
      -
        url: https://itunes.apple.com/app/id1055506207
        title: Скачать с App Store
      -
        url: https://github.com/yenbekbay/metio
        title: Посмотреть исходный код 
  -
    title: Never Drink Alone
    description: iOS приложение, которое предлагает одно деловое знакомство в день с самыми интересными людьми вашего города (Проект закрыт).
    image: nda.png
    year: 2015-2015
    links:
      -
        url: https://github.com/yenbekbay/never-drink-alone
        title: Посмотреть исходный код
  -
    title: Kogershin
    description: iOS приложение, позволяющее вам следить за вашими посылками через сервис Казпочты (Проект закрыт).
    image: kogershin.png
    year: 2015-2017
    links:
      -
        url: https://github.com/yenbekbay/kogershin
        title: Посмотреть исходный код 
  -
    title: Galileo
    description: iOS приложение для чтения избранных статей из Википедии (Проект закрыт).
    image: galileo.png
    year: 2015-2016
    links:
      -
        url: https://github.com/yenbekbay/galileo
        title: Посмотреть исходный код
  -
    title: Instamaniac
    description: iOS приложение для просмотра нестандартной статистики вашего аккаунта в Инстаграме (Проект закрыт).
    image: instamaniac.png
    year: 2015-2016
    links:
      -
        url: https://github.com/yenbekbay/instamaniac
        title: Посмотреть исходный код

# URL
url: https://yenbekbay.me
root: /
permalink: blog/:title/
permalink_defaults:

# Directories
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
code_dir: blog/downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Categories & tags
default_category: uncategorized
category_map:
category_generator:
  per_page: 0
tag_map:
tag_generator:
  per_page: 0

# Blog
index_generator:
  path: blog
  per_page: 10
  order_by: -date

# RSS
feed:
  type: atom
  path: blog/atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml

# Archives
archive_generator:
  per_page: 0

# Minification
html_minifier:
  enable: true
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  exclude:
    - '*.min.js'
image_minifier:
  enable: false

# Markdown-it
## https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/
markdown: default

# Date & time
## https://momentjs.com/docs/#/displaying/format/
date_format: LL
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page
