## Docs: http://hexo.io/docs/configuration.html

# Site
title: Аян Енбекбай
description: iOS, дизайн, продуктивность
theme: clean-blog
author: Аян Енбекбай
language: ru
first_name: Аян
last_name: Енбекбай
twitter: yenbekbay
facebook: yenbekbay
email: ayan.yenb@gmail.com
gender: male
fb_admins: 100002863455345
google_analytics: UA-68104290-1
favicon: /images/favicon.png
default_backdrop: almaty_from_ski_jumping_hill.jpg
menu_title: '@yenbekbay'
timezone:

# Footer links
links:
  -
    title: Twitter
    url: //twitter.com/yenbekbay
    icon: twitter
  -
    title: GitHub
    url: //github.com/yenbekbay
    icon: github
  -
    title: Instagram
    url: //instagram.com/yenbekbay
    icon: instagram
  -
    title: Vimeo
    url: //vimeo.com/yenbekbay
    icon: vimeo

# Menu
menu:
  -
    title: Blog
    url: /
  -
    title: About
    url: //yenbekbay.me
  -
    title: Timelapses
    url: //yenbekbay.me/timelapses

# URL
url: http://blog.yenbekbay.me
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Category & tag
default_category: uncategorized
category_map:
tag_map:

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml

# Archive
archive_generator:
  per_page: 0

# Minification

html_minifier:
  enable: false

css_minifier:
  enable: true
  exclude:
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  exclude:
    - '*.min.js'

image_minifier:
  enable: false

beautify:
  types:
    - html
  html:
    indent_inner_html: false
    indent_size: 2
    indent_with_tabs: false
    max_preserve_newlines: 0

# Date & time
## http://momentjs.com/docs/#/displaying/format/
date_format: LL
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Deployment
deploy:
  type: git
  repository: git@github.com:yenbekbay/blog.yenbekbay.me.git
  branch: gh-pages
